doctrine_migrations:
    migrations-paths:
        'App\Migrations': '%kernel.project_dir%/src/Migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
            version_column_name: 'version'
            version_column_length: 192
            executed_at_column_name: 'executed_at'
            execution_time_column_name: 'execution_time'
