sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user: App\Application\Sonata\UserBundle\Entity\User
        group: App\Application\Sonata\UserBundle\Entity\Group
    impersonating:
        route: sonata_admin_dashboard
    mailer: app.user_mailer
