name: app

type: php:7.4

relationships:
    database: "mydatabase:mysql"
    redis: "myredis:redis"

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - iconv
        - ctype
        - pdo_mysql
        - redis
        

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: /app/config/preload.php

build:
    flavor: none

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }
    "/public/upload/media/default": { source: local, source_path: default }

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

crons:
    mendeley_download:
        # Download LiveGeneShare publications from Mendeley every Sunday at noon
        spec: '0 12 * * 0'
        cmd: |
            if [ "$SYMFONY_BRANCH" = "master" ]; then
                croncape symfony console app:mendeley:download
            fi
    mendeley_new_publications_notifier:
        # Notify LiveGene members about new publications at Mendeley every Monday at 3am
        spec: '0 3 * * 1'
        cmd: |
            if [ "$SYMFONY_BRANCH" = "master" ]; then
                croncape symfony console app:mendeley:new-publications-notifier
            fi
    organisation_logo_check_status:
        # Check the status code of the organisation logos every Sunday and Wednesday midnight
        spec: '0 0 * * 0,3'
        cmd: |
            if [ "$SYMFONY_BRANCH" = "master" ]; then
                croncape symfony console app:organisation:check-logo-status
            fi
