name: app

type: php:7.4

relationships:
    database: "mydatabase:mysql"

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - iconv
        - ctype
        - pdo_mysql
        

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: /app/config/preload.php

build:
    flavor: none

disk: 512

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }
    "/public/upload": { source: local, source_path: upload }

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
